version: 2
updates:

  # Docker base images
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      time: "11:00"
    open-pull-requests-limit: 25

  # GitHub Actions workflows
  - package-ecosystem: github-actions
    directory: ".github/workflows"
    schedule:
      interval: monthly
      time: "11:00"
    open-pull-requests-limit: 25

  # Gradle (Java dependencies)
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: monthly
      time: "11:00"
    open-pull-requests-limit: 25
